<?php
// database/seeders/DemoTradingSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class DemoTradingSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Demo User
        DB::table('users')->updateOrInsert(
            ['email' => 'demo@trader.com'],
            [
                'name'              => 'Demo Trader',
                'email'             => 'demo@trader.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ]
        );

        $userId = DB::table('users')->where('email', 'demo@trader.com')->value('id');

        // 2. Funding Plan
        $planId = DB::table('funding_plans')->insertGetId([
            'title'           => '10K Evaluation',
            'capital'         => 1000000.00,
            'fee'             => 15000.00,
            'profit_target'   => '8%',
            'max_loss'        => '6%',
            'drawdown_type'   => 'Trailing',
            'payout_cycle'    => '20 Days',
            'news_trading'    => 1,
            'weekend_holding' => 1,
            'is_active'       => 1,
            'sort_order'      => 1,
            'created_at'      => now(),
            'updated_at'      => now(),
        ]);

        // 3. Active Challenge
        $challengeId = DB::table('challenges')->insertGetId([
            'user_id'                     => $userId,
            'plan_id'                     => $planId,
            'capacity_value'              => 1000000.00,
            'start_balance'               => 1000000.00,
            'current_balance'             => 1035075.00,
            'peak_balance'                => 1052000.00,
            'total_profit'                => 35075.00,
            'total_loss'                  => 0.00,
            'daily_drawdown'              => 0.00,
            'overall_drawdown'            => 0.00,
            'phase'                       => 1,
            'status'                      => 'active',
            'min_days_required'           => 5,
            'valid_days_completed_days'   => 3,
            'max_trading_days'            => null,
            'trading_days_elapsed'        => 4,
            'profit_target_percent'       => 8.00,
            'max_daily_loss_percent'      => 5.00,
            'max_overall_loss_percent'    => 10.00,
            'current_daily_loss_percent'  => 0.00,
            'current_overall_loss_percent'=> 0.00,
            'next_payout_eligible_at'     => null,
            'payout_amount'               => 0.00,
            'last_payout_at'              => null,
            'started_at'                  => Carbon::now()->subDays(4),
            'ended_at'                    => null,
            'passed_at'                   => null,
            'failed_at'                   => null,
            'account_id'                  => 'DEMO-' . strtoupper(Str::random(8)),
            'meta'                        => json_encode(['seeder' => true]),
            'is_demo'                     => true,
            'created_at'                  => now(),
            'updated_at'                  => now(),
        ]);

        // 4. Orders (4 realistic orders – all columns included)
        DB::table('orders')->insert([
            [
                'user_id'            => $userId,
                'challenge_id'       => $challengeId,
                'stock_symbol'       => 'RELIANCE',
                'security_id'        => '1333',
                'order_side'         => 1,
                'order_type'         => 2,
                'product_type'       => 'INTRADAY',
                'price'              => 0.00,
                'trigger_price'      => null,
                'quantity'           => 15,
                'disclosed_quantity' => 0,
                'filled_quantity'    => 15,
                'filled_percentage'  => 100,
                'average_price'      => 2575.75,
                'total_amount'       => 38636.25,
                'brokerage'          => 20.00,
                'status'             => 1,
                'trx'                => '412307150001',
                'parent_order_id'    => null,
                'correlation_id'     => (string) Str::uuid(),
                'placed_by'          => 'user',
                'meta'               => null,
                'created_at'         => now()->subDays(3),
                'updated_at'         => now()->subDays(3),
            ],
            [
                'user_id'            => $userId,
                'challenge_id'       => $challengeId,
                'stock_symbol'       => 'TCS',
                'security_id'        => '11536',
                'order_side'         => 2,
                'order_type'         => 1,
                'product_type'       => 'INTRADAY',
                'price'              => 3780.00,
                'trigger_price'          => null,
                'quantity'           => 8,
                'disclosed_quantity' => 0,
                'filled_quantity'    => 8,
                'filled_percentage'  => 100,
                'average_price'      => 3780.00,
                'total_amount'       => 30240.00,
                'brokerage'          => 15.00,
                'status'             => 1,
                'trx'                => '412307150045',
                'parent_order_id'    => null,
                'correlation_id'     => (string) Str::uuid(),
                'placed_by'          => 'user',
                'meta'               => null,
                'created_at'         => now()->subDays(2),
                'updated_at'         => now()->subDays(2),
            ],
            [
                'user_id'            => $userId,
                'challenge_id'       => $challengeId,
                'stock_symbol'       => 'INFY',
                'security_id'        => '1594',
                'order_side'         => 1,
                'order_type'         => 1,
                'product_type'       => 'INTRADAY',
                'price'              => 1420.00,
                'trigger_price'      => null,
                'quantity'           => 25,
                'disclosed_quantity' => 0,
                'filled_quantity'    => 0,
                'filled_percentage'  => 0,
                'average_price'      => null,
                'total_amount'       => null,
                'brokerage'          => 0.00,
                'status'             => 0,
                'trx'                => '412307160089',
                'parent_order_id'    => null,
                'correlation_id'     => (string) Str::uuid(),
                'placed_by'          => 'user',
                'meta'               => null,
                'created_at'         => now()->subHours(4),
                'updated_at'         => now()->subHours(4),
            ],
            [
                'user_id'            => $userId,
                'challenge_id'       => $challengeId,
                'stock_symbol'       => 'HDFCBANK',
                'security_id'        => '1330',
                'order_side'         => 2,
                'order_type'         => 3,
                'product_type'       => 'INTRADAY',
                'price'              => 1650.00,
                'trigger_price'      => 1640.00,
                'quantity'           => 20,
                'disclosed_quantity' => 0,
                'filled_quantity'    => 20,
                'filled_percentage'    => 100,
                'average_price'      => 1642.50,
                'total_amount'       => 32850.00,
                'brokerage'          => 18.00,
                'status'             => 1,
                'trx'                => '412307160112',
                'parent_order_id'    => null,
                'correlation_id'     => (string) Str::uuid(),
                'placed_by'          => 'user',
                'meta'               => json_encode(['sl_hit' => true]),
                'created_at'         => now()->subDays(1),
                'updated_at'         => now()->subDays(1),
            ],
        ]);

        // 5. trade_logs – EXACT COLUMN ORDER & FULL DATA
        DB::table('trade_logs')->insert([
            // Trade 1
            [
                'uuid'                  => Str::uuid(),
                'user_id'               => $userId,
                'challenge_id'          => $challengeId,
                'strategy_id'           => null,
                'symbol'                => 'RELIANCE',
                'direction'             => 'long',
                'entry_price'           => 2575.75,
                'exit_price'            => 2610.00,
                'entry_time'            => Carbon::now()->subDays(3)->setHour(10)->setMinute(15),
                'exit_time'             => Carbon::now()->subDays(3)->setHour(14)->setMinute(30),
                'quantity'             => 15,
                'profit_loss'           => 513.75,
                'profit_loss_percent'   => 1.33,
                'commission'            => 20.00,
                'swap'                  => 0.00,
                'stop_loss'             => null,
                'take_profit'           => 2650.00,
                'stop_loss_used'        => false,
                'take_profit_used'      => true,
                'trailing_stop_used'    => false,
                'slippage'              => 0.25,
                'holding_seconds'       => 19800,
                'trade_type'            => 'intraday',
                'exchange'              => 'NSE',
                'segment'               => 'EQ',
                'order_ids'             => json_encode(['412307150001']),
                'broker_trade_ids'      => json_encode(['T202512070001']),
                'meta'                  => json_encode(['note' => 'Take profit hit', 'setup' => 'Breakout']),
                'is_paper'              => false,
                'delayed_feed'          => false,
                'closed_at'             => Carbon::now()->subDays(3)->setHour(14)->setMinute(30),
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            // Trade 2
            [
                'uuid'                  => Str::uuid(),
                'user_id'               => $userId,
                'challenge_id'          => $challengeId,
                'strategy_id'           => null,
                'symbol'                => 'HDFCBANK',
                'direction'             => 'short',
                'entry_price'           => 1642.50,
                'exit_price'            => 1630.00,
                'entry_time'            => Carbon::now()->subDays(1)->setHour(11)->setMinute(0),
                'exit_time'             => Carbon::now()->subDays(1)->setHour(13)->setMinute(45),
                'quantity'              => 20,
                'profit_loss'           => 250.00,
                'profit_loss_percent'   => 0.76,
                'commission'            => 18.00,
                'swap'                  => 0.00,
                'stop_loss'             => 1655.00,
                'take_profit'           => null,
                'stop_loss_used'             => false,
                'take_profit_used'      => false,
                'trailing_stop_used'    => false,
                'slippage'              => 0.50,
                'holding_seconds'       => 9900,
                'trade_type'            => 'intraday',
                'exchange'              => 'NSE',
                'segment'               => 'EQ',
                'order_ids'             => json_encode(['412307160112']),
                'broker_trade_ids'      => json_encode(['T202512080112']),
                'meta'                  => json_encode(['note' => 'Manual exit']),
                'is_paper'              => false,
                'delayed_feed'          => false,
                'closed_at'             => Carbon::now()->subDays(1)->setHour(13)->setMinute(45),
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
        ]);

        // 6. Legacy `trades` table
        DB::table('trades')->insert([
            [
                'challenge_id'          => $challengeId,
                'symbol'                => 'RELIANCE',
                'side'                  => 'buy',
                'qty'                   => 15,
                'entry_price'           => 2575.75,
                'exit_price'            => 2610.00,
                'pnl'                   => 513.75,
                'sl_used'               => false,
                'tp_used'               => true,
                'entry_time'            => Carbon::now()->subDays(3)->setHour(10)->setMinute(15),
                'exit_time'             => Carbon::now()->subDays(3)->setHour(14)->setMinute(30),
                'holding_time_seconds'  => 19800,
                'gap_seconds'           => 0,
                'news_flag'             => false,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'challenge_id'          => $challengeId,
                'symbol'                => 'HDFCBANK',
                'side'                  => 'sell',
                'qty'                   => 20,
                'entry_price'           => 1642.50,
                'exit_price'            => 1630.00,
                'pnl'                   => 250.00,
                'sl_used'               => false,
                'tp_used'               => false,
                'entry_time'            => Carbon::now()->subDays(1)->setHour(11)->setMinute(0),
                'exit_time'             => Carbon::now()->subDays(1)->setHour(13)->setMinute(45),
                'holding_time_seconds'  => 9900,
                'gap_seconds'           => 0,
                'news_flag'             => false,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
        ]);

        $this->command->info('Demo data seeded PERFECTLY!');
        $this->command->info('Login: demo@trader.com / password');
        $this->command->info('Balance: ₹10,35,075 | Profit: ₹35,075');
        $this->command->info('2 closed trades in trade_logs + trades table');
    }
}
