<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Instrument;

class InstrumentsSeeder extends Seeder
{
    public function run()
    {
        $instruments = [
            ['symbol' => 'FSI-NF50', 'category' => 'index', 'sector' => 'broad_market', 'base_price' => 22850, 'volatility_class' => 'medium', 'tick_size' => 0.5, 'lot_size' => 25, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-BN', 'category' => 'index', 'sector' => 'banking', 'base_price' => 48700, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 15, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-FN', 'category' => 'index', 'sector' => 'financial_services', 'base_price' => 21300, 'volatility_class' => 'medium', 'tick_size' => 0.5, 'lot_size' => 40, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-MD', 'category' => 'index', 'sector' => 'midcap', 'base_price' => 10200, 'volatility_class' => 'medium', 'tick_size' => 0.5, 'lot_size' => 75, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-SC', 'category' => 'index', 'sector' => 'smallcap', 'base_price' => 13300, 'volatility_class' => 'medium', 'tick_size' => 0.5, 'lot_size' => 75, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-SX', 'category' => 'index', 'sector' => 'broad_market', 'base_price' => 75800, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 10, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-BX', 'category' => 'index', 'sector' => 'banking', 'base_price' => 57300, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 15, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-HDFC', 'category' => 'stock', 'sector' => 'banking', 'base_price' => 1580, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 550, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-ICBK', 'category' => 'stock', 'sector' => 'banking', 'base_price' => 1100, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 700, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-SBN', 'category' => 'stock', 'sector' => 'banking', 'base_price' => 820, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 750, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-AXS', 'category' => 'stock', 'sector' => 'banking', 'base_price' => 1130, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 625, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-KOT', 'category' => 'stock', 'sector' => 'banking', 'base_price' => 1780, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 400, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-BJF', 'category' => 'stock', 'sector' => 'financial', 'base_price' => 7250, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 125, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-PNBF', 'category' => 'stock', 'sector' => 'financial', 'base_price' => 1120, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 650, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-IDBF', 'category' => 'stock', 'sector' => 'banking', 'base_price' => 98, 'volatility_class' => 'high', 'tick_size' => 0.01, 'lot_size' => 10000, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-TCSX', 'category' => 'stock', 'sector' => 'information_technology', 'base_price' => 3890, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 175, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-INFY', 'category' => 'stock', 'sector' => 'information_technology', 'base_price' => 1650, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 300, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-WPRO', 'category' => 'stock', 'sector' => 'information_technology', 'base_price' => 520, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 1500, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-HCLT', 'category' => 'stock', 'sector' => 'information_technology', 'base_price' => 1360, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 350, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-LTIM', 'category' => 'stock', 'sector' => 'information_technology', 'base_price' => 4950, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 125, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-TECHM', 'category' => 'stock', 'sector' => 'information_technology', 'base_price' => 1320, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 400, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-RLI', 'category' => 'stock', 'sector' => 'energy', 'base_price' => 2950, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 250, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-ONG', 'category' => 'stock', 'sector' => 'energy', 'base_price' => 275, 'volatility_class' => 'high', 'tick_size' => 0.01, 'lot_size' => 7700, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-BPCL', 'category' => 'stock', 'sector' => 'energy', 'base_price' => 465, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 1800, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-HPCL', 'category' => 'stock', 'sector' => 'energy', 'base_price' => 410, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 1950, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-IOC', 'category' => 'stock', 'sector' => 'energy', 'base_price' => 138, 'volatility_class' => 'high', 'tick_size' => 0.01, 'lot_size' => 9750, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-GAIL', 'category' => 'stock', 'sector' => 'energy', 'base_price' => 175, 'volatility_class' => 'medium', 'tick_size' => 0.01, 'lot_size' => 6100, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-TTM', 'category' => 'stock', 'sector' => 'automobile', 'base_price' => 960, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 550, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-MRT', 'category' => 'stock', 'sector' => 'automobile', 'base_price' => 12700, 'volatility_class' => 'medium', 'tick_size' => 5, 'lot_size' => 100, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-MM', 'category' => 'stock', 'sector' => 'automobile', 'base_price' => 1930, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 300, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-BJAT', 'category' => 'stock', 'sector' => 'automobile', 'base_price' => 6450, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 125, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-ESC', 'category' => 'stock', 'sector' => 'automobile', 'base_price' => 990, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 400, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-ITC', 'category' => 'stock', 'sector' => 'fmcg', 'base_price' => 455, 'volatility_class' => 'low', 'tick_size' => 0.05, 'lot_size' => 1600, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-HUL', 'category' => 'stock', 'sector' => 'fmcg', 'base_price' => 2580, 'volatility_class' => 'low', 'tick_size' => 0.05, 'lot_size' => 300, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-NSTL', 'category' => 'stock', 'sector' => 'fmcg', 'base_price' => 22850, 'volatility_class' => 'low', 'tick_size' => 5, 'lot_size' => 50, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-DABR', 'category' => 'stock', 'sector' => 'fmcg', 'base_price' => 560, 'volatility_class' => 'low', 'tick_size' => 0.05, 'lot_size' => 1250, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-GCM', 'category' => 'stock', 'sector' => 'fmcg', 'base_price' => 730, 'volatility_class' => 'low', 'tick_size' => 0.05, 'lot_size' => 1500, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-TSTL', 'category' => 'stock', 'sector' => 'metal', 'base_price' => 162, 'volatility_class' => 'high', 'tick_size' => 0.01, 'lot_size' => 4250, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-JSW', 'category' => 'stock', 'sector' => 'metal', 'base_price' => 905, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 675, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-HDAL', 'category' => 'stock', 'sector' => 'metal', 'base_price' => 505, 'volatility_class' => 'high', 'tick_size' => 0.05, 'lot_size' => 1700, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-COAL', 'category' => 'stock', 'sector' => 'metal', 'base_price' => 425, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 1800, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-NALC', 'category' => 'stock', 'sector' => 'metal', 'base_price' => 185, 'volatility_class' => 'high', 'tick_size' => 0.01, 'lot_size' => 8200, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-SUNP', 'category' => 'stock', 'sector' => 'pharma', 'base_price' => 1450, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 350, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-DRD', 'category' => 'stock', 'sector' => 'pharma', 'base_price' => 5450, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 125, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-DIVS', 'category' => 'stock', 'sector' => 'pharma', 'base_price' => 3950, 'volatility_class' => 'medium', 'tick_size' => 0.5, 'lot_size' => 200, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-CIPL', 'category' => 'stock', 'sector' => 'pharma', 'base_price' => 1480, 'volatility_class' => 'medium', 'tick_size' => 0.05, 'lot_size' => 400, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-APLO', 'category' => 'stock', 'sector' => 'pharma', 'base_price' => 6300, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 125, 'session_start' => '09:15:00', 'session_end' => '15:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-GLD', 'category' => 'commodity', 'sector' => 'bullion', 'base_price' => 66500, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 100, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-GLDM', 'category' => 'commodity', 'sector' => 'bullion', 'base_price' => 6650, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 10, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-SLV', 'category' => 'commodity', 'sector' => 'bullion', 'base_price' => 74000, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 30, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-SLVM', 'category' => 'commodity', 'sector' => 'bullion', 'base_price' => 7400, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 5, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-CRD', 'category' => 'commodity', 'sector' => 'energy', 'base_price' => 7200, 'volatility_class' => 'very_high', 'tick_size' => 1, 'lot_size' => 100, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-CRDM', 'category' => 'commodity', 'sector' => 'energy', 'base_price' => 720, 'volatility_class' => 'very_high', 'tick_size' => 1, 'lot_size' => 10, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-NGS', 'category' => 'commodity', 'sector' => 'energy', 'base_price' => 240, 'volatility_class' => 'very_high', 'tick_size' => 0.1, 'lot_size' => 1250, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-COP', 'category' => 'commodity', 'sector' => 'metal', 'base_price' => 760, 'volatility_class' => 'high', 'tick_size' => 0.5, 'lot_size' => 2500, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-ZNC', 'category' => 'commodity', 'sector' => 'metal', 'base_price' => 260, 'volatility_class' => 'high', 'tick_size' => 0.1, 'lot_size' => 5000, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-ALU', 'category' => 'commodity', 'sector' => 'metal', 'base_price' => 225, 'volatility_class' => 'medium', 'tick_size' => 0.1, 'lot_size' => 5000, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-LED', 'category' => 'commodity', 'sector' => 'metal', 'base_price' => 210, 'volatility_class' => 'high', 'tick_size' => 0.1, 'lot_size' => 5000, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-NKL', 'category' => 'commodity', 'sector' => 'metal', 'base_price' => 1480, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 250, 'session_start' => '09:00:00', 'session_end' => '23:30:00', 'news_sensitivity' => 'very_high', 'is_active' => true],
            ['symbol' => 'FSI-CTN', 'category' => 'commodity', 'sector' => 'agriculture', 'base_price' => 62000, 'volatility_class' => 'high', 'tick_size' => 1, 'lot_size' => 25, 'session_start' => '10:00:00', 'session_end' => '21:00:00', 'news_sensitivity' => 'high', 'is_active' => true],
            ['symbol' => 'FSI-MTH', 'category' => 'commodity', 'sector' => 'agriculture', 'base_price' => 5500, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 100, 'session_start' => '10:00:00', 'session_end' => '21:00:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-CRN', 'category' => 'commodity', 'sector' => 'agriculture', 'base_price' => 2450, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 100, 'session_start' => '10:00:00', 'session_end' => '21:00:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-SOY', 'category' => 'commodity', 'sector' => 'agriculture', 'base_price' => 5100, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 100, 'session_start' => '10:00:00', 'session_end' => '21:00:00', 'news_sensitivity' => 'medium', 'is_active' => true],
            ['symbol' => 'FSI-RICE', 'category' => 'commodity', 'sector' => 'agriculture', 'base_price' => 3820, 'volatility_class' => 'medium', 'tick_size' => 1, 'lot_size' => 100, 'session_start' => '10:00:00', 'session_end' => '21:00:00', 'news_sensitivity' => 'medium', 'is_active' => true],
        ];

        foreach ($instruments as $data) {
            Instrument::updateOrCreate(['symbol' => $data['symbol']], $data);
        }
    }
}
